org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home
systemProp.org.gradle.internal.http.connectionTimeout=15000
systemProp.org.gradle.internal.http.socketTimeout=15000