// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initSearchEngine({required String indexPath}) =>
    RustLib.instance.api.crateApiSearchInitSearchEngine(indexPath: indexPath);

Future<void> upsertNoteIndex(
        {required PlatformInt64 id,
        required String title,
        required String content}) =>
    RustLib.instance.api
        .crateApiSearchUpsertNoteIndex(id: id, title: title, content: content);

Future<void> deleteNoteIndex({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiSearchDeleteNoteIndex(id: id);

Future<List<SearchHit>> searchNotes(
        {required String query, required int limit}) =>
    RustLib.instance.api.crateApiSearchSearchNotes(query: query, limit: limit);

Future<void> rebuildIndex({required List<NoteForIndex> notes}) =>
    RustLib.instance.api.crateApiSearchRebuildIndex(notes: notes);

class NoteForIndex {
  final PlatformInt64 id;
  final String title;
  final String plainText;

  const NoteForIndex({
    required this.id,
    required this.title,
    required this.plainText,
  });

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ plainText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteForIndex &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          plainText == other.plainText;
}

class SearchHit {
  final PlatformInt64 noteId;
  final double score;
  final String titleHighlight;
  final String contentSnippet;

  const SearchHit({
    required this.noteId,
    required this.score,
    required this.titleHighlight,
    required this.contentSnippet,
  });

  @override
  int get hashCode =>
      noteId.hashCode ^
      score.hashCode ^
      titleHighlight.hashCode ^
      contentSnippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          noteId == other.noteId &&
          score == other.score &&
          titleHighlight == other.titleHighlight &&
          contentSnippet == other.contentSnippet;
}
